version: '3.9'
services:
  app:
    labels:
      # Включаем traefik для текущего сервиса
      - traefik.enable=true
      # Объявляем порт сервиса в докере для прослушки
      - traefik.http.services.frontend.loadbalancer.server.port=3000
      # Настройка маршрута для фронтенда
      - traefik.http.routers.frontend.rule=Host(`brick-nn.sbs`) && PathPrefix(`/`)
      # Настройка для HTTPS
      - traefik.http.routers.frontend.entrypoints=https
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certresolver=le
      # Объявляем миддлвейр редиректа с HTTP на HTTPS
      - traefik.http.middlewares.frontend-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.frontend-https-redirect.redirectscheme.permanent=true
      # Устанавливаем миддлвейр редиректа с HTTP на HTTPS
      - traefik.http.routers.frontend-http.middlewares=frontend-https-redirect
      - traefik.http.routers.frontend-http.rule=Host(`brick-nn.sbs`) && PathPrefix(`/`)
      - traefik.http.routers.frontend-http.entrypoints=http
      # Говорим traefik использовать объявленную публичную сеть
      - traefik.docker.network=traefik-public
    networks:
      - traefik-public
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      target: base
    expose:
        - "3000"
    env_file:
      - .env
    command: ["npm", "run", "start"]

networks:
  traefik-public:
    external: true
